#!/usr/bin/env python3
"""
SportMind skill freshness checker.
Monitors competition format sources for changes that may require skill file updates.
Called by .github/workflows/skill-monitor.yml every Monday at 9am UTC.

Reads monitoring sources from platform/monitoring-sources.json.
Creates GitHub issues for skills that appear stale.

See platform/monitoring-alerts.md (Alert 4: Competition format change) for alert specs.
See platform/live-signals.md (self-update signals) for what triggers a review.

Usage:
    python scripts/check_skill_freshness.py \\
        --sources platform/monitoring-sources.json \\
        --create-issues-if-stale \\
        --stale-threshold-days 90
"""

import argparse
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False


def load_sources(sources_file: str) -> dict:
    """Load monitoring sources configuration."""
    try:
        with open(sources_file) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"ERROR: Cannot load {sources_file}: {e}")
        sys.exit(1)


def check_source_freshness(source: dict, stale_days: int) -> dict:
    """
    Check whether a monitored source has been updated recently.
    
    NOTE: Full implementation requires:
    1. Storing last-checked timestamps per source
    2. Fetching the source URL and checking for structural changes
    3. Comparing against expected content patterns
    
    This stub logs what would be checked and returns a placeholder result.
    For production implementation, integrate with a web scraping or 
    RSS feed monitoring service.
    """
    print(f"  Checking: {source['name']} ({source['url']})")
    print(f"    Sport: {source.get('sport', 'all')}")
    print(f"    Skills affected: {', '.join(source.get('skills_affected', []))}")
    print(f"    Monitoring for: {', '.join(source.get('monitor_for', []))}")

    # Placeholder: In production, fetch URL and check for keyword changes
    # Return "not_stale" until actual monitoring is implemented
    return {
        "source_id": source["id"],
        "status": "not_stale",
        "last_checked": datetime.now(timezone.utc).isoformat(),
        "note": "Full monitoring requires web scraping integration (see implementation guide)"
    }


def create_github_issue(source: dict, reason: str, token: str = None) -> None:
    """Create a GitHub issue for a stale skill."""
    if not token:
        print(f"    WOULD CREATE ISSUE: {source['name']} — {reason}")
        print(f"    Skills: {', '.join(source.get('skills_affected', []))}")
        return

    # GitHub API issue creation
    # Requires: GITHUB_TOKEN with issues:write permission
    import os
    repo = os.environ.get("GITHUB_REPOSITORY", "SportMind/SportMind")
    
    issue_body = f"""## Automated skill review alert

**Source:** {source['name']}
**URL:** {source['url']}
**Reason:** {reason}

**Skills potentially affected:**
{chr(10).join(f'- `{s}`' for s in source.get('skills_affected', []))}

**What to check:**
{chr(10).join(f'- {item}' for item in source.get('monitor_for', []))}

**Action required:**
1. Visit {source['url']} and check for {', '.join(source.get('monitor_for', []))}
2. If changes found, update the affected skill files
3. Close this issue when skill files are updated

*Generated by scripts/check_skill_freshness.py via skill-monitor.yml*
"""
    
    if HAS_REQUESTS and token:
        headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json"}
        payload = {
            "title": f"[Skill Review] {source['name']} — {reason}",
            "body": issue_body,
            "labels": ["skill-review-needed", "automated"]
        }
        try:
            resp = requests.post(
                f"https://api.github.com/repos/{repo}/issues",
                json=payload, headers=headers, timeout=10
            )
            if resp.status_code == 201:
                print(f"    Issue created: #{resp.json()['number']}")
            else:
                print(f"    Issue creation failed: {resp.status_code}")
        except Exception as e:
            print(f"    Issue creation error: {e}")


def main():
    parser = argparse.ArgumentParser(description="SportMind skill freshness checker")
    parser.add_argument("--sources", default="platform/monitoring-sources.json")
    parser.add_argument("--create-issues-if-stale", action="store_true")
    parser.add_argument("--stale-threshold-days", type=int, default=90)
    args = parser.parse_args()

    import os
    github_token = os.environ.get("GITHUB_TOKEN")

    print(f"\n=== SportMind Skill Freshness Check ===")
    print(f"Time: {datetime.now(timezone.utc).isoformat()}")
    print(f"Stale threshold: {args.stale_threshold_days} days")
    print()

    config = load_sources(args.sources)
    all_sources = (
        config.get("competition_format_sources", []) +
        config.get("partnership_sources", []) +
        config.get("regulatory_sources", [])
    )

    results = []
    stale_count = 0

    for source in all_sources:
        print(f"\nSource: {source['id']}")
        result = check_source_freshness(source, args.stale_threshold_days)
        results.append(result)

        if result["status"] == "stale":
            stale_count += 1
            if args.create_issues_if_stale:
                create_github_issue(source, "Source appears stale", github_token)

    print(f"\n=== Summary ===")
    print(f"Sources checked: {len(results)}")
    print(f"Stale: {stale_count}")
    print(f"All current: {len(results) - stale_count}")
    print("\nNOTE: Full HTTP monitoring requires web scraping integration.")
    print("See platform/monitoring-alerts.md for implementation guidance.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
